#include "keycode.h"
#include <SDL3/SDL_scancode.h>

namespace Seed {

int SeedKey_To_SDL(int seed_keycode) {
    switch (seed_keycode) {
    case Seed_KeyA:
        return SDL_SCANCODE_A;
    case Seed_KeyB:
        return SDL_SCANCODE_B;
    case Seed_KeyC:
        return SDL_SCANCODE_C;
    case Seed_KeyD:
        return SDL_SCANCODE_D;
    case Seed_KeyE:
        return SDL_SCANCODE_E;
    case Seed_KeyF:
        return SDL_SCANCODE_F;
    case Seed_KeyG:
        return SDL_SCANCODE_G;
    case Seed_KeyH:
        return SDL_SCANCODE_H;
    case Seed_KeyI:
        return SDL_SCANCODE_I;
    case Seed_KeyJ:
        return SDL_SCANCODE_J;
    case Seed_KeyK:
        return SDL_SCANCODE_K;
    case Seed_KeyL:
        return SDL_SCANCODE_L;
    case Seed_KeyM:
        return SDL_SCANCODE_M;
    case Seed_KeyN:
        return SDL_SCANCODE_N;
    case Seed_KeyO:
        return SDL_SCANCODE_O;
    case Seed_KeyP:
        return SDL_SCANCODE_P;
    case Seed_KeyQ:
        return SDL_SCANCODE_Q;
    case Seed_KeyR:
        return SDL_SCANCODE_R;
    case Seed_KeyS:
        return SDL_SCANCODE_S;
    case Seed_KeyT:
        return SDL_SCANCODE_T;
    case Seed_KeyU:
        return SDL_SCANCODE_U;
    case Seed_KeyV:
        return SDL_SCANCODE_V;
    case Seed_KeyW:
        return SDL_SCANCODE_W;
    case Seed_KeyX:
        return SDL_SCANCODE_X;
    case Seed_KeyY:
        return SDL_SCANCODE_Y;
    case Seed_KeyZ:
        return SDL_SCANCODE_Z;

    case Seed_Key0:
        return SDL_SCANCODE_0;
    case Seed_Key1:
        return SDL_SCANCODE_1;
    case Seed_Key2:
        return SDL_SCANCODE_2;
    case Seed_Key3:
        return SDL_SCANCODE_3;
    case Seed_Key4:
        return SDL_SCANCODE_4;
    case Seed_Key5:
        return SDL_SCANCODE_5;
    case Seed_Key6:
        return SDL_SCANCODE_6;
    case Seed_Key7:
        return SDL_SCANCODE_7;
    case Seed_Key8:
        return SDL_SCANCODE_8;
    case Seed_Key9:
        return SDL_SCANCODE_9;

    case Seed_KeyF1:
        return SDL_SCANCODE_F1;
    case Seed_KeyF2:
        return SDL_SCANCODE_F2;
    case Seed_KeyF3:
        return SDL_SCANCODE_F3;
    case Seed_KeyF4:
        return SDL_SCANCODE_F4;
    case Seed_KeyF5:
        return SDL_SCANCODE_F5;
    case Seed_KeyF6:
        return SDL_SCANCODE_F6;
    case Seed_KeyF7:
        return SDL_SCANCODE_F7;
    case Seed_KeyF8:
        return SDL_SCANCODE_F8;
    case Seed_KeyF9:
        return SDL_SCANCODE_F9;
    case Seed_KeyF10:
        return SDL_SCANCODE_F10;
    case Seed_KeyF11:
        return SDL_SCANCODE_F11;
    case Seed_KeyF12:
        return SDL_SCANCODE_F12;
    case Seed_KeyF13:
        return SDL_SCANCODE_F13;
    case Seed_KeyF14:
        return SDL_SCANCODE_F14;
    case Seed_KeyF15:
        return SDL_SCANCODE_F15;
    case Seed_KeyF16:
        return SDL_SCANCODE_F16;
    case Seed_KeyF17:
        return SDL_SCANCODE_F17;
    case Seed_KeyF18:
        return SDL_SCANCODE_F18;
    case Seed_KeyF19:
        return SDL_SCANCODE_F19;
    case Seed_KeyF20:
        return SDL_SCANCODE_F20;
    case Seed_KeyF21:
        return SDL_SCANCODE_F21;
    case Seed_KeyF22:
        return SDL_SCANCODE_F22;
    case Seed_KeyF23:
        return SDL_SCANCODE_F23;
    case Seed_KeyF24:
        return SDL_SCANCODE_F24;

    case Seed_KeyLeftShift:
        return SDL_SCANCODE_LSHIFT;
    case Seed_KeyRightShift:
        return SDL_SCANCODE_RSHIFT;
    case Seed_KeyLeftCtrl:
        return SDL_SCANCODE_LCTRL;
    case Seed_KeyRightCtrl:
        return SDL_SCANCODE_RCTRL;
    case Seed_KeyLeftAlt:
        return SDL_SCANCODE_LALT;
    case Seed_KeyRightAlt:
        return SDL_SCANCODE_RALT;
    case Seed_KeyLeftSuper:
        return SDL_SCANCODE_LGUI;
    case Seed_KeyRightSuper:
        return SDL_SCANCODE_RGUI;

    case Seed_KeySpace:
        return SDL_SCANCODE_SPACE;
    case Seed_KeyTab:
        return SDL_SCANCODE_TAB;
    case Seed_KeyCapsLock:
        return SDL_SCANCODE_CAPSLOCK;
    case Seed_KeyNumLock:
        return SDL_SCANCODE_NUMLOCKCLEAR;
    case Seed_KeyScrollLock:
        return SDL_SCANCODE_SCROLLLOCK;

    case Seed_KeyEscape:
        return SDL_SCANCODE_ESCAPE;
    case Seed_KeyEnter:
        return SDL_SCANCODE_RETURN;
    case Seed_KeyBackspace:
        return SDL_SCANCODE_BACKSPACE;
    case Seed_KeyDelete:
        return SDL_SCANCODE_DELETE;
    case Seed_KeyInsert:
        return SDL_SCANCODE_INSERT;
    case Seed_KeyHome:
        return SDL_SCANCODE_HOME;
    case Seed_KeyEnd:
        return SDL_SCANCODE_END;
    case Seed_KeyPageUp:
        return SDL_SCANCODE_PAGEUP;
    case Seed_KeyPageDown:
        return SDL_SCANCODE_PAGEDOWN;

    case Seed_KeyUp:
        return SDL_SCANCODE_UP;
    case Seed_KeyDown:
        return SDL_SCANCODE_DOWN;
    case Seed_KeyLeft:
        return SDL_SCANCODE_LEFT;
    case Seed_KeyRight:
        return SDL_SCANCODE_RIGHT;

    case Seed_KeyComma:
        return SDL_SCANCODE_COMMA;
    case Seed_KeyPeriod:
        return SDL_SCANCODE_PERIOD;
    case Seed_KeySlash:
        return SDL_SCANCODE_SLASH;
    case Seed_KeySemicolon:
        return SDL_SCANCODE_SEMICOLON;
    case Seed_KeyQuote:
        return SDL_SCANCODE_APOSTROPHE;
    case Seed_KeyLeftBracket:
        return SDL_SCANCODE_LEFTBRACKET;
    case Seed_KeyRightBracket:
        return SDL_SCANCODE_RIGHTBRACKET;
    case Seed_KeyBackslash:
        return SDL_SCANCODE_BACKSLASH;
    case Seed_KeyGraveAccent:
        return SDL_SCANCODE_GRAVE;
    case Seed_KeyMinus:
        return SDL_SCANCODE_MINUS;
    case Seed_KeyEqual:
        return SDL_SCANCODE_EQUALS;

    case Seed_KeyNumpad0:
        return SDL_SCANCODE_KP_0;
    case Seed_KeyNumpad1:
        return SDL_SCANCODE_KP_1;
    case Seed_KeyNumpad2:
        return SDL_SCANCODE_KP_2;
    case Seed_KeyNumpad3:
        return SDL_SCANCODE_KP_3;
    case Seed_KeyNumpad4:
        return SDL_SCANCODE_KP_4;
    case Seed_KeyNumpad5:
        return SDL_SCANCODE_KP_5;
    case Seed_KeyNumpad6:
        return SDL_SCANCODE_KP_6;
    case Seed_KeyNumpad7:
        return SDL_SCANCODE_KP_7;
    case Seed_KeyNumpad8:
        return SDL_SCANCODE_KP_8;
    case Seed_KeyNumpad9:
        return SDL_SCANCODE_KP_9;
    case Seed_KeyNumpadDecimal:
        return SDL_SCANCODE_KP_DECIMAL;
    case Seed_KeyNumpadDivide:
        return SDL_SCANCODE_KP_DIVIDE;
    case Seed_KeyNumpadMultiply:
        return SDL_SCANCODE_KP_MULTIPLY;
    case Seed_KeyNumpadSubtract:
        return SDL_SCANCODE_KP_MINUS;
    case Seed_KeyNumpadAdd:
        return SDL_SCANCODE_KP_PLUS;
    case Seed_KeyNumpadEnter:
        return SDL_SCANCODE_KP_ENTER;

    default:
        return 0; // SDL_SCANCODE_UNKNOWN
    }
}

int SDLKey_To_Seed(int sdl_scancode) {
    switch (sdl_scancode) {
    case SDL_SCANCODE_A:
        return Seed_KeyA;
    case SDL_SCANCODE_B:
        return Seed_KeyB;
    case SDL_SCANCODE_C:
        return Seed_KeyC;
    case SDL_SCANCODE_D:
        return Seed_KeyD;
    case SDL_SCANCODE_E:
        return Seed_KeyE;
    case SDL_SCANCODE_F:
        return Seed_KeyF;
    case SDL_SCANCODE_G:
        return Seed_KeyG;
    case SDL_SCANCODE_H:
        return Seed_KeyH;
    case SDL_SCANCODE_I:
        return Seed_KeyI;
    case SDL_SCANCODE_J:
        return Seed_KeyJ;
    case SDL_SCANCODE_K:
        return Seed_KeyK;
    case SDL_SCANCODE_L:
        return Seed_KeyL;
    case SDL_SCANCODE_M:
        return Seed_KeyM;
    case SDL_SCANCODE_N:
        return Seed_KeyN;
    case SDL_SCANCODE_O:
        return Seed_KeyO;
    case SDL_SCANCODE_P:
        return Seed_KeyP;
    case SDL_SCANCODE_Q:
        return Seed_KeyQ;
    case SDL_SCANCODE_R:
        return Seed_KeyR;
    case SDL_SCANCODE_S:
        return Seed_KeyS;
    case SDL_SCANCODE_T:
        return Seed_KeyT;
    case SDL_SCANCODE_U:
        return Seed_KeyU;
    case SDL_SCANCODE_V:
        return Seed_KeyV;
    case SDL_SCANCODE_W:
        return Seed_KeyW;
    case SDL_SCANCODE_X:
        return Seed_KeyX;
    case SDL_SCANCODE_Y:
        return Seed_KeyY;
    case SDL_SCANCODE_Z:
        return Seed_KeyZ;

    case SDL_SCANCODE_0:
        return Seed_Key0;
    case SDL_SCANCODE_1:
        return Seed_Key1;
    case SDL_SCANCODE_2:
        return Seed_Key2;
    case SDL_SCANCODE_3:
        return Seed_Key3;
    case SDL_SCANCODE_4:
        return Seed_Key4;
    case SDL_SCANCODE_5:
        return Seed_Key5;
    case SDL_SCANCODE_6:
        return Seed_Key6;
    case SDL_SCANCODE_7:
        return Seed_Key7;
    case SDL_SCANCODE_8:
        return Seed_Key8;
    case SDL_SCANCODE_9:
        return Seed_Key9;

    case SDL_SCANCODE_F1:
        return Seed_KeyF1;
    case SDL_SCANCODE_F2:
        return Seed_KeyF2;
    case SDL_SCANCODE_F3:
        return Seed_KeyF3;
    case SDL_SCANCODE_F4:
        return Seed_KeyF4;
    case SDL_SCANCODE_F5:
        return Seed_KeyF5;
    case SDL_SCANCODE_F6:
        return Seed_KeyF6;
    case SDL_SCANCODE_F7:
        return Seed_KeyF7;
    case SDL_SCANCODE_F8:
        return Seed_KeyF8;
    case SDL_SCANCODE_F9:
        return Seed_KeyF9;
    case SDL_SCANCODE_F10:
        return Seed_KeyF10;
    case SDL_SCANCODE_F11:
        return Seed_KeyF11;
    case SDL_SCANCODE_F12:
        return Seed_KeyF12;
    case SDL_SCANCODE_F13:
        return Seed_KeyF13;
    case SDL_SCANCODE_F14:
        return Seed_KeyF14;
    case SDL_SCANCODE_F15:
        return Seed_KeyF15;
    case SDL_SCANCODE_F16:
        return Seed_KeyF16;
    case SDL_SCANCODE_F17:
        return Seed_KeyF17;
    case SDL_SCANCODE_F18:
        return Seed_KeyF18;
    case SDL_SCANCODE_F19:
        return Seed_KeyF19;
    case SDL_SCANCODE_F20:
        return Seed_KeyF20;
    case SDL_SCANCODE_F21:
        return Seed_KeyF21;
    case SDL_SCANCODE_F22:
        return Seed_KeyF22;
    case SDL_SCANCODE_F23:
        return Seed_KeyF23;
    case SDL_SCANCODE_F24:
        return Seed_KeyF24;

    case SDL_SCANCODE_LSHIFT:
        return Seed_KeyLeftShift;
    case SDL_SCANCODE_RSHIFT:
        return Seed_KeyRightShift;
    case SDL_SCANCODE_LCTRL:
        return Seed_KeyLeftCtrl;
    case SDL_SCANCODE_RCTRL:
        return Seed_KeyRightCtrl;
    case SDL_SCANCODE_LALT:
        return Seed_KeyLeftAlt;
    case SDL_SCANCODE_RALT:
        return Seed_KeyRightAlt;
    case SDL_SCANCODE_LGUI:
        return Seed_KeyLeftSuper;
    case SDL_SCANCODE_RGUI:
        return Seed_KeyRightSuper;

    case SDL_SCANCODE_SPACE:
        return Seed_KeySpace;
    case SDL_SCANCODE_TAB:
        return Seed_KeyTab;
    case SDL_SCANCODE_CAPSLOCK:
        return Seed_KeyCapsLock;
    case SDL_SCANCODE_NUMLOCKCLEAR:
        return Seed_KeyNumLock;
    case SDL_SCANCODE_SCROLLLOCK:
        return Seed_KeyScrollLock;

    case SDL_SCANCODE_ESCAPE:
        return Seed_KeyEscape;
    case SDL_SCANCODE_RETURN:
        return Seed_KeyEnter;
    case SDL_SCANCODE_BACKSPACE:
        return Seed_KeyBackspace;
    case SDL_SCANCODE_DELETE:
        return Seed_KeyDelete;
    case SDL_SCANCODE_INSERT:
        return Seed_KeyInsert;
    case SDL_SCANCODE_HOME:
        return Seed_KeyHome;
    case SDL_SCANCODE_END:
        return Seed_KeyEnd;
    case SDL_SCANCODE_PAGEUP:
        return Seed_KeyPageUp;
    case SDL_SCANCODE_PAGEDOWN:
        return Seed_KeyPageDown;

    case SDL_SCANCODE_UP:
        return Seed_KeyUp;
    case SDL_SCANCODE_DOWN:
        return Seed_KeyDown;
    case SDL_SCANCODE_LEFT:
        return Seed_KeyLeft;
    case SDL_SCANCODE_RIGHT:
        return Seed_KeyRight;

    case SDL_SCANCODE_COMMA:
        return Seed_KeyComma;
    case SDL_SCANCODE_PERIOD:
        return Seed_KeyPeriod;
    case SDL_SCANCODE_SLASH:
        return Seed_KeySlash;
    case SDL_SCANCODE_SEMICOLON:
        return Seed_KeySemicolon;
    case SDL_SCANCODE_APOSTROPHE:
        return Seed_KeyQuote;
    case SDL_SCANCODE_LEFTBRACKET:
        return Seed_KeyLeftBracket;
    case SDL_SCANCODE_RIGHTBRACKET:
        return Seed_KeyRightBracket;
    case SDL_SCANCODE_BACKSLASH:
        return Seed_KeyBackslash;
    case SDL_SCANCODE_GRAVE:
        return Seed_KeyGraveAccent;
    case SDL_SCANCODE_MINUS:
        return Seed_KeyMinus;
    case SDL_SCANCODE_EQUALS:
        return Seed_KeyEqual;

    case SDL_SCANCODE_KP_0:
        return Seed_KeyNumpad0;
    case SDL_SCANCODE_KP_1:
        return Seed_KeyNumpad1;
    case SDL_SCANCODE_KP_2:
        return Seed_KeyNumpad2;
    case SDL_SCANCODE_KP_3:
        return Seed_KeyNumpad3;
    case SDL_SCANCODE_KP_4:
        return Seed_KeyNumpad4;
    case SDL_SCANCODE_KP_5:
        return Seed_KeyNumpad5;
    case SDL_SCANCODE_KP_6:
        return Seed_KeyNumpad6;
    case SDL_SCANCODE_KP_7:
        return Seed_KeyNumpad7;
    case SDL_SCANCODE_KP_8:
        return Seed_KeyNumpad8;
    case SDL_SCANCODE_KP_9:
        return Seed_KeyNumpad9;
    case SDL_SCANCODE_KP_DECIMAL:
        return Seed_KeyNumpadDecimal;
    case SDL_SCANCODE_KP_DIVIDE:
        return Seed_KeyNumpadDivide;
    case SDL_SCANCODE_KP_MULTIPLY:
        return Seed_KeyNumpadMultiply;
    case SDL_SCANCODE_KP_MINUS:
        return Seed_KeyNumpadSubtract;
    case SDL_SCANCODE_KP_PLUS:
        return Seed_KeyNumpadAdd;
    case SDL_SCANCODE_KP_ENTER:
        return Seed_KeyNumpadEnter;

    default:
        return Seed_Unknown;
    }
}

int ImGuiKey_To_Seed(int imgui_keycode) {
    switch (imgui_keycode) {
    case 546:
        return Seed_KeyA;
    case 547:
        return Seed_KeyB;
    case 548:
        return Seed_KeyC;
    case 549:
        return Seed_KeyD;
    case 550:
        return Seed_KeyE;
    case 551:
        return Seed_KeyF;
    case 552:
        return Seed_KeyG;
    case 553:
        return Seed_KeyH;
    case 554:
        return Seed_KeyI;
    case 555:
        return Seed_KeyJ;
    case 556:
        return Seed_KeyK;
    case 557:
        return Seed_KeyL;
    case 558:
        return Seed_KeyM;
    case 559:
        return Seed_KeyN;
    case 560:
        return Seed_KeyO;
    case 561:
        return Seed_KeyP;
    case 562:
        return Seed_KeyQ;
    case 563:
        return Seed_KeyR;
    case 564:
        return Seed_KeyS;
    case 565:
        return Seed_KeyT;
    case 566:
        return Seed_KeyU;
    case 567:
        return Seed_KeyV;
    case 568:
        return Seed_KeyW;
    case 569:
        return Seed_KeyX;
    case 570:
        return Seed_KeyY;
    case 571:
        return Seed_KeyZ;

    case 536:
        return Seed_Key0;
    case 537:
        return Seed_Key1;
    case 538:
        return Seed_Key2;
    case 539:
        return Seed_Key3;
    case 540:
        return Seed_Key4;
    case 541:
        return Seed_Key5;
    case 542:
        return Seed_Key6;
    case 543:
        return Seed_Key7;
    case 544:
        return Seed_Key8;
    case 545:
        return Seed_Key9;

    case 572:
        return Seed_KeyF1;
    case 573:
        return Seed_KeyF2;
    case 574:
        return Seed_KeyF3;
    case 575:
        return Seed_KeyF4;
    case 576:
        return Seed_KeyF5;
    case 577:
        return Seed_KeyF6;
    case 578:
        return Seed_KeyF7;
    case 579:
        return Seed_KeyF8;
    case 580:
        return Seed_KeyF9;
    case 581:
        return Seed_KeyF10;
    case 582:
        return Seed_KeyF11;
    case 583:
        return Seed_KeyF12;
    case 584:
        return Seed_KeyF13;
    case 585:
        return Seed_KeyF14;
    case 586:
        return Seed_KeyF15;
    case 587:
        return Seed_KeyF16;
    case 588:
        return Seed_KeyF17;
    case 589:
        return Seed_KeyF18;
    case 590:
        return Seed_KeyF19;
    case 591:
        return Seed_KeyF20;
    case 592:
        return Seed_KeyF21;
    case 593:
        return Seed_KeyF22;
    case 594:
        return Seed_KeyF23;
    case 595:
        return Seed_KeyF24;

    case 528:
        return Seed_KeyLeftShift;
    case 532:
        return Seed_KeyRightShift;
    case 527:
        return Seed_KeyLeftCtrl;
    case 531:
        return Seed_KeyRightCtrl;
    case 529:
        return Seed_KeyLeftAlt;
    case 533:
        return Seed_KeyRightAlt;
    case 530:
        return Seed_KeyLeftSuper;
    case 534:
        return Seed_KeyRightSuper;

    case 524:
        return Seed_KeySpace;
    case 512:
        return Seed_KeyTab;
    case 607:
        return Seed_KeyCapsLock;
    case 609:
        return Seed_KeyNumLock;
    case 608:
        return Seed_KeyScrollLock;

    case 526:
        return Seed_KeyEscape;
    case 525:
        return Seed_KeyEnter;
    case 523:
        return Seed_KeyBackspace;
    case 522:
        return Seed_KeyDelete;
    case 521:
        return Seed_KeyInsert;
    case 519:
        return Seed_KeyHome;
    case 520:
        return Seed_KeyEnd;
    case 517:
        return Seed_KeyPageUp;
    case 518:
        return Seed_KeyPageDown;

    case 515:
        return Seed_KeyUp;
    case 516:
        return Seed_KeyDown;
    case 513:
        return Seed_KeyLeft;
    case 514:
        return Seed_KeyRight;

    case 597:
        return Seed_KeyComma;
    case 599:
        return Seed_KeyPeriod;
    case 600:
        return Seed_KeySlash;
    case 601:
        return Seed_KeySemicolon;
    case 596:
        return Seed_KeyQuote;
    case 603:
        return Seed_KeyLeftBracket;
    case 605:
        return Seed_KeyRightBracket;
    case 604:
        return Seed_KeyBackslash;
    case 606:
        return Seed_KeyGraveAccent;
    case 598:
        return Seed_KeyMinus;
    case 602:
        return Seed_KeyEqual;

    case 612:
        return Seed_KeyNumpad0;
    case 613:
        return Seed_KeyNumpad1;
    case 614:
        return Seed_KeyNumpad2;
    case 615:
        return Seed_KeyNumpad3;
    case 616:
        return Seed_KeyNumpad4;
    case 617:
        return Seed_KeyNumpad5;
    case 618:
        return Seed_KeyNumpad6;
    case 619:
        return Seed_KeyNumpad7;
    case 620:
        return Seed_KeyNumpad8;
    case 621:
        return Seed_KeyNumpad9;
    case 622:
        return Seed_KeyNumpadDecimal;
    case 623:
        return Seed_KeyNumpadDivide;
    case 624:
        return Seed_KeyNumpadMultiply;
    case 625:
        return Seed_KeyNumpadSubtract;
    case 626:
        return Seed_KeyNumpadAdd;
    case 627:
        return Seed_KeyNumpadEnter;

    default:
        return Seed_Unknown;
    }
}

} // namespace Seed
